name: Build Ship of Harkinian nightly
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools
            ports/soh-nightly
          sparse-checkout-cone-mode: false
      - name: Build port
        run: |
          . ./tools/build_port.txt ports/soh-nightly/soh-nightly
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create git tag and upload
        run: |
          git config --global user.email "ben@willmore.eu"
          git config --global user.name "Github Action"
          git pull origin
          git add ports/soh-nightly
          git commit -m "SoH nightly build ${{ steps.date.outputs.date }}"
          git tag SoH-nightly-${{ steps.date.outputs.date }}
          git push origin tag SoH-nightly-${{ steps.date.outputs.date }}
          git push origin
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SoH-Portmaster-nightly
          path: |
            ports/soh-nightly/Ship of Harkinian nightly.sh
            ports/soh-nightly/soh-nightly
          retention-days: 7
          overwrite: true
          include-hidden-files: true