name: Build Starship nightly
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'

env:
  PORT_NAME: "Starship"
  SHORT_NAME: "Starship"
  PORT_DIR: starship-nightly
  BUILD_TYPE: nightly
  EMAIL: ben@willmore.eu

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools
            ports/${{ env.PORT_DIR }}
          sparse-checkout-cone-mode: false
      - name: Build port
        run: |
          . ./tools/build_port.txt ports/${{ env.PORT_DIR }}/${{ env.PORT_DIR }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create git tag and upload
        run: |
          git config --global user.email "${{ env.EMAIL }}"
          git config --global user.name "Github Action"
          git pull origin
          git add ports/${{ env.PORT_DIR }}
          git commit -m "${{ env.SHORT_NAME }} ${{ env.BUILD_TYPE }} build ${{ steps.date.outputs.date }}"
          # git tag ${{ env.SHORT_NAME }}-${{ env.BUILD_TYPE }}-${{ steps.date.outputs.date }}
          git push origin
          # git push --delete origin :refs/tags/${{ env.SHORT_NAME }}-${{ env.BUILD_TYPE }}-${{ steps.date.outputs.date }}

      # - name: Publish packaged artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.SHORT_NAME }}-Portmaster
      #     path: |
      #       ports/${{ env.PORT_DIR }}/*.sh
      #       ports/${{ env.PORT_DIR }}/${{ env.PORT_DIR }}
      #     retention-days: 7
      #     overwrite: true
      #     include-hidden-files: true

      - name: Create zip file
        run: |
          cd ports/${{ env.PORT_DIR }}
          zip -r ${{ env.PORT_DIR }}.zip *.sh ${{ env.PORT_DIR }}
      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SHORT_NAME }}-${{ env.BUILD_TYPE }}-latest"
          prerelease: true
          title: "${{ env.SHORT_NAME }}-${{ env.BUILD_TYPE }}-${{ steps.date.outputs.date }}"
          files: |
            ports/${{ env.PORT_DIR }}/*.zip