name: Build Ship of Harkinian
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ports/soh
          sparse-checkout-cone-mode: false
      - name: Build port
        run: |
          . ./tools/build_port.txt ports/soh/soh          
