name: Build Ship of Harkinian
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools
            ports/soh
          sparse-checkout-cone-mode: false
      - name: Build port
        run: |
          pwd
          # . ./tools/build_port.txt ports/soh/soh
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SoH-Portmaster
          path: |
            "~/ports/soh/*.sh"
            "~/ports/soh/soh"
          retention-days: 7
          overwrite: true
          include-hidden-files: true