name: Build Ship of Harkinian 2 (S2H2)
on:
  # Build on request
  workflow_dispatch
#  schedule:
#    - cron:  '5 4 * * *'
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tools
            ports/soh2
          sparse-checkout-cone-mode: false
      - name: Build port
        run: |
          . ./tools/build_port.txt ports/soh2/soh2
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SoH2-Portmaster
          path: |
            "ports/soh2/Ship of Harkinian 2.sh"
            "ports/soh2/soh2"
          retention-days: 7
          overwrite: true
          include-hidden-files: true