name: Build Ship of Harkinian 2
on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '5 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/build_port.yaml
    with:
      port-name: "Ship of Harkinian 2"
      short-name: SoH2
      port-dir: soh2
      build-type: release
      email: ben@willmore.eu
